[project]
name = "codic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prithvi Kaushik", email = "prithvik.work@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "marimo>=0.25.0",
    "nbformat>=5.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
codic = "codic:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
